# Generated by Django 6.0.3 on 2026-03-22 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('episodios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faturacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EPISODIO_ATUAL', 'Episódio Atual'), ('EPISODIO_PASSADO', 'Episódio Passado')], max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_registo', models.DateTimeField(auto_now_add=True)),
                ('pago', models.BooleanField(default=False)),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturacoes', to='episodios.episodiourgencia')),
            ],
        ),
    ]
