# Generated by Django 6.0.3 on 2026-03-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_utente', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('nif', models.CharField(max_length=9, unique=True)),
                ('morada', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=12)),
                ('telefone', models.CharField(max_length=20)),
                ('contacto_terceiro_nome', models.CharField(max_length=150)),
                ('contacto_terceiro_telefone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
