# Generated by Django 6.0.3 on 2026-03-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_internamento', models.DateTimeField()),
                ('data_alta_hospitalar', models.DateTimeField(blank=True, null=True)),
                ('servico', models.CharField(max_length=100)),
                ('cama', models.CharField(max_length=20)),
                ('terapeutica_atual', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumoDiarioInternamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resumo', models.DateField()),
                ('resumo', models.TextField()),
            ],
        ),
    ]
