# Generated by Django 6.0.3 on 2026-03-22 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('episodios', '0002_initial'),
        ('internamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internamento',
            name='enfermeiro_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internamentos_como_enfermeiro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internamento',
            name='episodio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internamento', to='episodios.episodiourgencia'),
        ),
        migrations.AddField(
            model_name='internamento',
            name='medico_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internamentos_como_medico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumodiariointernamento',
            name='internamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumos_diarios', to='internamentos.internamento'),
        ),
        migrations.AlterUniqueTogether(
            name='resumodiariointernamento',
            unique_together={('internamento', 'data_resumo')},
        ),
    ]
