# Generated by Django 6.0.3 on 2026-03-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internamentos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internamento',
            name='observacoes_transferencia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
