# Generated by Django 6.0.3 on 2026-03-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodioUrgencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_entrada', models.DateTimeField()),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True)),
                ('motivo_admissao', models.TextField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('prioridade_manchester', models.CharField(choices=[('VERMELHO', 'Vermelho - Emergente'), ('LARANJA', 'Laranja - Muito urgente'), ('AMARELO', 'Amarelo - Urgente'), ('VERDE', 'Verde - Pouco urgente'), ('AZUL', 'Azul - Não urgente')], max_length=20)),
                ('estado_atual', models.CharField(choices=[('AGUARDA_OBSERVACAO', 'Aguarda Observação médica'), ('AGUARDA_EXAME', 'Aguarda realização de exame'), ('AGUARDA_RESULTADO', 'Aguarda resultado do exame'), ('AGUARDA_TERAPEUTICA', 'Aguarda realização terapêutica'), ('AGUARDA_INTERNAMENTO', 'Aguarda internamento'), ('INTERNADO', 'Internado'), ('ALTA', 'Alta'), ('ENCERRADO', 'Encerrado')], default='AGUARDA_OBSERVACAO', max_length=30)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tempo_previsivel_alta', models.DateTimeField(blank=True, null=True)),
                ('fechado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('localizacao', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_triagem', models.DateTimeField()),
                ('cor_manchester', models.CharField(choices=[('VERMELHO', 'Vermelho - Emergente'), ('LARANJA', 'Laranja - Muito urgente'), ('AMARELO', 'Amarelo - Urgente'), ('VERDE', 'Verde - Pouco urgente'), ('AZUL', 'Azul - Não urgente')], max_length=20)),
                ('sintomas', models.TextField()),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
