# Generated by Django 6.0.3 on 2026-03-22 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('episodios', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='episodiourgencia',
            name='enfermeiro_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodios_como_enfermeiro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='episodiourgencia',
            name='medico_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodios_como_medico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='episodiourgencia',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='pacientes.utente'),
        ),
        migrations.AddField(
            model_name='episodiourgencia',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='episodios', to='episodios.hospital'),
        ),
        migrations.AddField(
            model_name='triagem',
            name='enfermeiro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triagens_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triagem',
            name='episodio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triagem', to='episodios.episodiourgencia'),
        ),
    ]
