# Generated by Django 6.0.3 on 2026-03-23 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodios', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('tipo_consulta', models.CharField(choices=[('OBSERVACAO_INICIAL', 'Observação inicial'), ('REAVALIACAO', 'Reavaliação'), ('CONSULTA_ESPECIALIDADE', 'Consulta de especialidade')], max_length=30)),
                ('resumo_clinico', models.TextField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='episodios.episodiourgencia')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('tipo_prescricao', models.CharField(choices=[('MEDICACAO', 'Medicação'), ('TERAPEUTICA', 'Terapêutica'), ('ORIENTACAO', 'Orientação clínica')], max_length=20)),
                ('descricao', models.TextField()),
                ('ativa', models.BooleanField(default=True)),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescricoes', to='episodios.episodiourgencia')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescricoes_emitidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
