# Generated by Django 6.0.3 on 2026-03-22 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('episodios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_exame', models.CharField(choices=[('ANALISES', 'Análises'), ('RX', 'Raio-X'), ('TAC', 'TAC'), ('RM', 'Ressonância Magnética'), ('ECOGRAFIA', 'Ecografia'), ('ECG', 'Eletrocardiograma'), ('OUTRO', 'Outro')], max_length=20)),
                ('descricao', models.TextField()),
                ('data_pedido', models.DateTimeField()),
                ('data_realizacao', models.DateTimeField(blank=True, null=True)),
                ('data_resultado', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PEDIDO', 'Pedido'), ('EM_EXECUCAO', 'Em execução'), ('CONCLUIDO', 'Concluído'), ('RESULTADO_DISPONIVEL', 'Resultado disponível')], default='PEDIDO', max_length=25)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='episodios.episodiourgencia')),
            ],
        ),
    ]
